src/backends/reactivemp.jl
=> feat: add `RequireMarginal` pipeline support

src/graph_engine.jl, src/model_macro.jl, test/graph_engine.jl
Now in line with new model macro
=> Refactored getifcreated

src/model_macro.jl, test/graph_engine.jl, test/model_macro.jl
Anonymous variables are now possible, however very limited. Limitations are documented in broken tests. Will fix later
=> Anonymous variables initial implementation

src/model_macro.jl, test/model_macro.jl
With this, also fixed expression in RHS bug, where all tests now pass. Walk until first occurrence is not possible, however, to solve the bug where "local" does not appear in the "created_by" clause.
=> Walk until first occurrence implemented

Project.toml, src/graph_engine.jl, src/model_macro.jl, test/Project.toml, test/graph_engine.jl, test/model_macro.jl, test/runtests.jl
Also some hygiene in seperating test from prod environment. Updated MetaGraph constructor to work with new release of MetaGraphsNext
=> Node initialization possible with any known function

src/model_macro.jl, test/model_macro.jl
More robust error handling and bug fixed that broke function-as-argument.
=> Function-as-argument bug fixed; refactored kwargs expression

src/graph_engine.jl, src/model_macro.jl, src/resizable_array.jl, test/graph_engine.jl, test/model_macro.jl, test/resizable_array.jl
Separates responsibilities of graph engine functions (no implicit side effects) and makes macro output more readable, is however, more code to maintain
=> Getorcreate split in getorcreate and createifnotexists

src/graph_engine.jl, src/model_macro.jl, test/graph_engine.jl, test/model_macro.jl
Getorcreate is now a lot more robust and shorter
=> Refactor getorcreate

src/graph_engine.jl, src/model_macro.jl, test/graph_engine.jl, test/model_macro.jl
=> Implemented Graph utility functions, added function aliasing system

.github/workflows/ci.yml
This PR adds Julia 1.9 in tests
=> use Julia 1.9 in tests

src/constraints_macro.jl, src/meta_macro.jl, src/model_macro.jl, test/model_macro.jl, test/model_zoo.jl
Should still come up with something better for this imo but for now this will do the job. Although it will restrict the user a bit in expressiveness. IMO not the final word on this
=> Removed return statements in model macro

src/constraints_engine.jl, src/graph_engine.jl, src/model_macro.jl, test/constraints_engine_tests.jl, test/graph_engine_tests.jl, test/model_macro_tests.jl
Patched bug in `haskey` which hid this bug in the first place.
=> Dev fix nonexisting constraint entry

src/constraints_engine.jl, src/graph_engine.jl, test/constraints_engine_tests.jl, test/graph_engine_tests.jl
Constraint materialization is slightly more explicit, now checks if a variable is either a constant or if it is a factorized data variable before factorizing it out of a local joint distribution.
=> `getorcreate!` accepts options for node creation

benchmark/model_zoo.jl, src/constraints_engine.jl, src/graph_engine.jl, src/meta_engine.jl, src/model_macro.jl, test/constraints_engine_tests.jl, test/graph_engine_tests.jl, test/meta_engine_tests.jl, test/model_macro_tests.jl
Should reduce memory footprint and runtime, although benchmarks seem broken.
=> All nodes equipped with `options` struct

README.md
Mostly just a test to test copilot automatic commit message generation and to test copilot chat's comprehension of a workspace
=> Update GraphPPL.jl documentation and installation instructions

src/graph_engine.jl, src/plugins/variational_constraints/variational_constraints_engine.jl, test/plugins/variational_constraints/variational_constraints_engine_tests.jl
10% faster model creation, 5% memory
=> Use same unique call for partition check and constraint materialization

test/graph_engine_tests.jl
Transferred some tests from ReactiveMP
=> More tests for Functional Index

test/graph_construction_tests.jl
=> Add more tests

src/backends/default.jl, src/graph_engine.jl, src/model_macro.jl, test/graph_construction_tests.jl, test/graph_engine_tests.jl
This PR fixes broadcasting over ranges. Also fixes a bug that we didn't even allow `1:end-1` apparently.
=> Dev 4.0.0 ranged broadcasting

Project.toml, docs/Project.toml, docs/make.jl, docs/src/constraint_specification.md, docs/src/custom_backend.md, docs/src/developers_guide.md, docs/src/getting_started.md, docs/src/nested_models.md, docs/src/plugins.md, docs/src/reference.md, ext/GraphPPLPlottingExt.jl, src/graph_engine.jl, src/model_macro.jl, src/plugins/variational_constraints/variational_constraints.jl, test/graph_construction_tests.jl, test/model_macro_tests.jl
Also contains a bug fix I found when making the docs compatible again
=> Documentation update

src/graph_engine.jl
up to 40% performance increase because of Julia magic
=> Make some structs mutable

Project.toml, docs/src/developers_guide.md, docs/src/plugins/node_id.md, docs/src/plugins/overview.md, src/graph_engine.jl, src/plugins/node_id.jl
=> A small patch for the documentation version 4.0.0

src/graph_engine.jl, test/graph_construction_tests.jl, test/graph_engine_tests.jl
=> Support "begin/end" indexing for ResizableArrays

src/resizable_array.jl, test/resizable_array_tests.jl
This PR is a pain in the *ss since you have to keep track of the state and handle accordingly. I'm open to suggestions on how to improve
=> reimplement iterate for resizablearray

Project.toml
=> Bump version to 4.0.1

src/graph_engine.jl, src/model_generator.jl, test/graph_construction_tests.jl, test/graph_engine_tests.jl
By using `Graphs.jl` internal functions for edge adding, model construction is 20% faster 🪄 🪄
=> Bug fix for duplicate arguments

src/graph_engine.jl, src/plugins/variational_constraints/variational_constraints_engine.jl, test/graph_engine_tests.jl, test/plugins/variational_constraints/variational_constraints_tests.jl
=> Fix issue 262

Project.toml, src/plugins/variational_constraints/variational_constraints.jl, test/plugins/variational_constraints/variational_constraints_tests.jl
That was missing from my previous PR. Also bumps version to 4.6.1
=> Add source code for MeanField and NoConstraints structures
