src/GraphPPL.jl
src/backends/reactivemp.jl

This PR adds `where {}` options syntax for randomvar, datavar and constvar functions.

feat(): where options support for datavar/constvar/datavar

---

src/backends/reactivemp.jl
src/model.jl
src/utils.jl
test/utils.jl

This PR adds aliases feature to model specification (`@model` macro):
See https://github.com/biaslab/ReactiveMP.jl/issues/1 and #17 
In the first version the following aliases are available:
`a || b`: alias for `OR(a, b)` node
`a && b`: alias for `AND(a, b)` node
`a -> b`: alias for `IMPLY(a, b)` node
`¬a` or `!a`: alias for `NOT(a)` node
`a + b + c`: alias for `(a + b) + c`
`Normal(μ|m|mean = ..., σ²|τ⁻¹|v|var|variance = ...)` alias for `NormalMeanVariance(..., ...)` node
`Normal(μ|m|mean = ..., τ|σ⁻²|w|p|prec|precision = ...)` alias for `NormalMeanVariance(..., ...)` node
`MvNormal(μ|m|mean = ..., Σ|V|Λ⁻¹|cov|covariance = ...)` alias for `MvNormalMeanCovariance(..., ...)` node
`MvNormal(μ|m|mean = ..., Λ|W|Σ⁻¹|prec|precision = ...)` alias for `MvNormalMeanPrecision(..., ...)` node …

Feature: aliases and keyword distribution specification in the model macro

---

src/backends/reactivemp.jl

This PR adds a new alias for the new `MvNormalMeanScalePrecision` node in ReactiveMP.jl

Add alias for `MvNormalMeanScalePrecision`

---

src/model.jl

This PR adds a new feature for the `@model` macro and allows passing priors as arguments to the model as:
```julia
@model function coin_model(n, prior)
y = datavar(Float64, n)
θ ~ prior
for i in 1:n
y[i] ~ Bernoulli(θ)
end
end
``

feat: priors as arguments support

---

src/graph_engine.jl
src/model_macro.jl
src/resizable_array.jl
test/graph_engine.jl
test/model_macro.jl
test/resizable_array.jl
test/runtests.jl

gensym now takes +- 2ns, compared to +- 200ns + `O(n)` in Base. Also fixed bug in ResizableArray.

Refactor gensym into gensym and generate_nodelabel

---

src/graph_engine.jl
src/resizable_array.jl
test/graph_engine.jl

Submodel now dynamically constructs based on the size of interfaces.
Also reimplemented iterator of `ResizableArray` such that we can iterate over vectors and tensors of random variables.

Reimplement `copy_markov_blanket_to_child_context`

---

src/graph_engine.jl
src/model_macro.jl
test/graph_engine.jl
test/model_macro.jl

`make_node!` now has better architecture that allows e.g. recursive model definition & default parameterizations (e.g. let `Normal(0 ,1)` dispatch to `NormalMeanVariance(\mu = 0, \sigma=1)`). Also precalculates any deterministic functions with known arguments as to not create any unnecessary nodes.

Refactor of `make_node!`

---

src/graph_engine.jl
test/graph_engine.jl

By implementing `GraphPPL.factor_alias` and `GraphPPL.rhs_to_named_tuple` we can determine which implementation of a distribution we would like to use (e.g. `NormalMeanVariance` when `Normal(μ, σ)` or `Normal(μ = μ, σ = σ)` is called and `NormalMeanPrecision` when `Normal(μ = μ, τ = τ)` is called.
MWE:
```
struct Normal end
struct NormalMeanVariance end
struct NormalMeanPrecision end
GraphPPL.interfaces(::Type{NormalMeanVariance}, ::Val{3}) = (:out, :μ, :σ)
GraphPPL.interfaces(::Type{NormalMeanPrecision}, ::Val{3}) = (:out, :μ, :τ)
GraphPPL.rhs_to_named_tuple(::GraphPPL.Atomic, ::Type{Normal}, rhs) = (μ = rhs[1], σ = rhs[2])
GraphPPL.factor_alias(::Type{Normal}, ::Val{(:μ, :σ)}) = NormalMeanVariance
GraphPPL.factor_alias(::Type{Normal}, ::Val{(:μ, :τ)}) = NormalMeanPrecision
@model …
```

Reimplemented parametrization flow

---

src/constraints_engine.jl
test/constraints_engine.jl

Makes stuff like 
```julia
q(x, y, z) = q(x, y)q(z)
q(x, y, z) = q(x)q(y, z)
q(x)::Normal
q(x)::Pointmass
```
illegal

Adding a constraint checks if it can be applied in current scope

---

src/constraints_engine.jl
src/graph_engine.jl
test/constraints_engine_tests.jl
test/graph_engine_tests.jl
test/integration_tests.jl

This PR improves the performance of the constraints application. Perhaps a lot more can be done, but this is also OK for now. On my small experiment I went from 
```
1.037032 seconds (13.11 M allocations: 609.419 MiB, 15.86% gc time)
```
to 
```
0.522466 seconds (7.28 M allocations: 284.243 MiB, 22.69% gc time)
```

Constraints performance

---

benchmark/model_creation.jl
src/constraints_engine.jl
src/graph_engine.jl
test/constraints_engine_tests.jl
test/graph_engine_tests.jl
test/meta_engine_tests.jl

Completely overhauls graph implementation so please don't merge yet. First discuss if we want to go down this road.

Factorization constraint outputs in the correct ordering

---

src/constraints_engine.jl
src/graph_engine.jl
test/constraints_engine_tests.jl
test/integration_tests.jl
test/model_zoo.jl

This PR adds the discussed tests and fixes a bug where if a constraint is applied to a node that has an anonymous variable that has two linked variables we didn't throw an error (and also if multiple variables were anonymous we'd throw). There's two things I'd like you to check @bvdmitri :
- There's a test failing in the anonymous variables code. According to me, it fails correctly and this test was wrong, but I'd rather that you double check.
- Constraints resolved and applied over deterministic nodes do nothing. We only apply constraints to stochastic nodes.

Patch constraints over anonymous variables bug

---

src/graph_engine.jl
src/plugins/meta/meta_engine.jl
src/plugins/variational_constraints/variational_constraints_engine.jl
test/graph_engine_tests.jl

This PR adds a special type of an object that can be used to query the `extra` properties of nodes in a factor graph at compile time, which additionally verifies the return type.

Add compile time keys for the extra properties of graph nodes

---

ext/GraphPPLDistributionsExt.jl
src/graph_engine.jl

Can you benchmark this @wouterwln , in my benchmarks it shows up to 2x speed up in some cases, which looks suspicious. 
It allocates slightly more in GraphPPL benchmarks, but benchmarks in RxInfer do not show any significant change in the performance nor in memory allocations.

Add type annotations to fform in more places

---

ext/GraphPPLDistributionsExt.jl
src/graph_engine.jl
test/graph_construction_tests.jl

Includes #163 (please merge #163 first)
A silly bug we missed, the fix is pretty easy though. 
~Didn't add the tests yet~ (added), but this is a reproducer
```julia
@model function mv_iid_inverse_wishart_known_mean(y, m, d)
C ~ InverseWishart(d + 1, diageye(d))
for i in eachindex(y)
y[i] ~ MvNormal(μ = m, Σ = C)
end
end
```
Without this PR the engine creates an anonymous random variable for `d + 1`, but it shouldn't (if `d` is a number and not a data).

Materialize anonymous variables later only if needed

---

src/model_macro.jl
test/graph_construction_tests.jl

This PR adds `NodeLabel` into the dispatch of `Composite` model creation. This way we can use anonymous variables on LHS, e.g. in the keyword arguments.

Allow submodels as keyword arguments 

---

src/plugins/variational_constraints/variational_constraints_engine.jl
test/plugins/variational_constraints/variational_constraints_tests.jl

This PR fixes the incorrect dispatch in the factorization constraints resolution. I'm not sure why the old dispatch didn't work though, but the fix seems to be simple and works just fine.

Fix incorrect dispatch in the factorization constraints resolution

---

src/plugins/variational_constraints/variational_constraints_engine.jl
src/plugins/variational_constraints/variational_constraints_macro.jl
test/plugins/variational_constraints/variational_constraints_engine_tests.jl
test/plugins/variational_constraints/variational_constraints_macro_tests.jl
test/plugins/variational_constraints/variational_constraints_tests.jl

This PR adds constant keys for marginal and messages form constraints. It also renames `posterior` -> `marginal` back after discussion with Ismail.

Add keys for marginal and messages form constraints

---

src/graph_engine.jl
test/graph_construction_tests.jl
test/graph_engine_tests.jl

This PR fixes cases where deterministic evaluation was invalid. E.g. in cases like
```julia
@model function broken_beta_bernoulli(y)
θ ~ Matrix([1.0 0.0; 0.0 1.0])
for i in eachindex(y)
y[i] ~ Bernoulli(θ)
end
end
```
The `Matrix([1.0 0.0; 0.0 1.0])` was evaluated and discarded. This PR fixes that, by allowing the evaluation of rhs only if the lhs is an anonymous variable. Such that this is still possible 
```julia
θ ~ MvNormal(mean = zeros(2), covariance = Matrix([1.0 0.0; 0.0 1.0]))
```

Fix invalid deterministic fform evaluation 

---

src/graph_engine.jl
src/plugins/variational_constraints/variational_constraints_engine.jl
test/graph_construction_tests.jl
test/plugins/variational_constraints/variational_constraints_engine_tests.jl

Relaxed dispatch of `check_variate_compatablility`
Now custom matrices are still a problem when we pass them to child contexts, but at least we throw a `NotImplementedError`

Allow passing of arbitrary vectors in submodels

---

src/graph_engine.jl
src/plugins/variational_constraints/variational_constraints_engine.jl
src/resizable_array.jl
test/graph_construction_tests.jl
test/graph_engine_tests.jl
test/plugins/variational_constraints/variational_constraints_engine_tests.jl
test/plugins/variational_constraints/variational_constraints_macro_tests.jl
test/plugins/variational_constraints/variational_constraints_tests.jl

This PR allows the following syntax:
```julia
@constraints begin
q(x, y) = MeanFieldI()
q(z) = MeanField()
end
```
While building this, I also found a bug. When `mat` is a matrix valued RV and the user specified:
```julia
@constraints begin
q(mat) = q(mat[begin])..q(mat[end])
end
```
and obscure error was thrown. Because of the way we encode ranges in the current implementation we actually don't allow multidimensional splitted ranges so a helpful error message will now be thrown.

Allow `MeanField` constraints

---

src/graph_engine.jl
test/graph_construction_tests.jl
test/graph_engine_tests.jl
test/plugins/variational_constraints/variational_constraints_engine_tests.jl

This PR re-implements a previously available feature within GraphPPL where data/const variables were creating data variable when used with anonymous deterministic fform

Fold data/const variables automatically with anonymous deterministic fform

---

src/GraphPPL.jl
src/backends/default.jl
src/graph_engine.jl
src/model_generator.jl
src/model_macro.jl
test/backends/default_tests.jl
test/model_generator_tests.jl
test/model_macro_tests.jl
test/testutils.jl

Requires some changes downstream, since we have to implement `instantiate` for custom backends and change the model macro

Add `with_backend` and allow parameterized backends

---

README.md

This PR changes the old link from BIASlab org to ReactiveBayes org

Fix old link in readme

---

src/graph_engine.jl
test/graph_construction_tests.jl

This PR fixes a missed use case for lazy node labels

Fix variate compatibility for lazy node label

---

Project.toml

This PR changes the `[compat]` entry to support Julia 1.10+. Closes #230

Set minimum required version of Julia to 1.10

---

src/graph_engine.jl
test/graph_construction_tests.jl

This PR addresses a bug found by @FraserP117 in #233 where constants increased the model counter twice and got two appendices for the NodeLabel. This implementation is a bit clunky, but it does the job.

Constants increase model counter twice

---

docs/src/plugins/constraint_specification.md
src/plugins/variational_constraints/variational_constraints_macro.jl
test/plugins/variational_constraints/variational_constraints_macro_tests.jl

This PR updates the stacked constraints to use tuples instead of the plus sign, which was an internal implementation detail of ReactiveMP. This change introduces minor breaking changes, but these were previously undocumented (this PR also adds the necessary documentation). Patches for ReactiveMP and RxInfer are forthcoming. After merging this PR, the minor version should be incremented.

Do not use the plus for stacked constraints

---

src/GraphPPL.jl
test/model_macro_tests.jl

This pull request introduces an error hint mechanism to guide users towards correct usage of the `:=` operator when creating new random variables and adds a corresponding test to ensure this functionality works as expected.
* [`src/GraphPPL.jl`](diffhunk://#diff-f882d3833959142b2fe2b34972ee335344fca1715059652f838da5d60ee93127R53-R68): Added an initialization function `__init__` to register an error hint for `MethodError` when `VariableRef` is used incorrectly, suggesting the use of the `:=` operator instead.
* [`test/model_macro_tests.jl`](diffhunk://#diff-d197d68d784bc5b1b2ca5a93f4529bc1ec682824a46476bbe2e20e8a75ea5caaR2033-R2045): Added a test case to verify that the error hint is triggered when a `VariableRef` is used incorrectly with the `=` operator.

Give a hint if a user uses = operator wrong

---

ext/GraphPPLGraphVizExt.jl

@FraserP117 gave me this idea in our private conversation and it actually worked pretty neatly!  
Reference https://docs.julialang.org/en/v1/base/io-network/#Multimedia-I/O
The implementation wraps the GraphViz object in a "wrapper" that does only "support" `svg` and `text` display formats. 
So now if display supports `svg` it will automatically show the svg image, otherwise it fallbacks to the dot strings as @FraserP117 planned originally. e.g compare:

Force svg+xml for GraphViz object as a workaround

---

benchmark/graph_engine.jl

This PR fixes `make bench` command. The benchmarks used outdated constructor for the `Model` struct that now also requires the `source_code` field to be set.

Fix benchmarks scripts

---

src/GraphPPL.jl
src/interfaces/edge_interface.jl
src/interfaces/factor_interface.jl
src/interfaces/model_interface.jl
src/interfaces/plugins_interface.jl
src/interfaces/variable_interface.jl
src/model/core/bipartitemodel.jl
src/model/core/edge_node_data.jl
src/model/core/factor_node_data.jl
src/model/core/variable_node_data.jl
test/model/core/edge_node_data_tests.jl
test/model/core/factor_node_data_tests.jl
test/model/core/variable_node_data_tests.jl

As from our discussion 
This pull request introduces updates to the interfaces of a factor graph library, focusing on renaming and restructuring core abstractions for edge, factor, and variable node data. The changes aim to improve clarity, extensibility, and type safety in the library's API. Below is a summary of the most important changes grouped by theme.
* Renamed `EdgeInterface` to `EdgeDataInterface` and updated all related functions (`get_name`, `get_index`, `has_extra`, etc.) to use the new type. This ensures consistency and better reflects the purpose of the interface.
* Updated the `add_edge!` and `get_edge_data_type` methods in `src/interfaces/model_interface.jl` to use `EdgeDataInterface` instead of `EdgeInterface`. [[1]](diffhunk://#diff-e1c959bfd4bc5ae74ddeecd194b6e11674798e0 …

Refine factor, variable and edge interfaces
